FROM ubuntu:18.04
# Add i386 support for support for Pin
RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y \
    python \
    screen \
    tmux \
    binutils \
	#ia32-libs \
	lib32ncurses5 \
	lib32z1 \
    libc6:i386 \
    libncurses5:i386 \
    libstdc++6:i386 \
 && rm -rf /var/lib/apt/lists/*
# For building Sniper
RUN apt-get update && apt-get install -y \
    automake \
    build-essential \
    curl \
    wget \
    libboost-dev \
    libsqlite3-dev \
    zlib1g-dev \
    libbz2-dev \
    g++-5 \
 && rm -rf /var/lib/apt/lists/*
# For building RISC-V Tools
RUN apt-get update && apt-get install -y \
    autoconf \
    automake \
    autotools-dev \
    bc \
    bison \
    curl \
    device-tree-compiler \
    flex \
    gawk \
    gperf \
    libexpat-dev \
    libgmp-dev \
    libmpc-dev \
    libmpfr-dev \
    libtool \
    libusb-1.0-0-dev \
    patchutils \
    pkg-config \
    texinfo \
    zlib1g-dev \
	software-properties-common \
 && rm -rf /var/lib/apt/lists/*
# Helper utilities
RUN apt-get update && add-apt-repository ppa:ubuntu-toolchain-r/test -y
# pip2, perf, etc
RUN apt-get update && apt-get install -y \
    gdb \
    gfortran \
    git \
	gcc-9 \
    g++-9 \
    vim \
    python-pip \
	time \
	python3-pip \
	linux-tools-common \
	linux-tools-generic \
	linux-cloud-tools-generic \
 && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9

RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9

RUN pip2 install --no-cache-dir  --upgrade pip && \
    pip2 install --no-cache-dir tabulate

RUN pip3 install --no-cache-dir  --upgrade pip && \
    pip3 install --no-cache-dir numpy
